server:
  port: 8082
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: employee
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: employee
            client-secret: b342da76-4ee6-417c-a490-03bf8c8260b5
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile, email, address, phone
            client-name: keycloak
        provider:
          keycloak:
            authorization-uri: http://localhost:8080/auth/realms/Mike/protocol/openid-connect/auth
            token-uri: http://localhost:8080/auth/realms/Mike/protocol/openid-connect/token
            user-info-uri:  http://localhost:8080/auth/realms/Mike/protocol/openid-connect/userinfo
            user-name-attribute: "preferred_username"
            jwk-set-uri: http://localhost:8080/auth/realms/Mike/protocol/openid-connect/certs